
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BHarat Nayak
 */
public class facultypro extends javax.swing.JFrame {

    /**
     * Creates new form facultypro
     */
    public facultypro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        cb3 = new javax.swing.JComboBox<>();
        cb4 = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t21 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t22 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t19 = new javax.swing.JTextField();
        t23 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t20 = new javax.swing.JTextField();
        t24 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cb5 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        t25 = new javax.swing.JTextField();
        t26 = new javax.swing.JTextField();
        t27 = new javax.swing.JTextField();
        t28 = new javax.swing.JTextField();
        t29 = new javax.swing.JTextField();
        t30 = new javax.swing.JTextField();
        t31 = new javax.swing.JTextField();
        t32 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        t33 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCHOOL MANAGEMENT SYSTEM: FACULTY PROFESSIONAL DETAILS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FACULTY PROFESSIONAL DETAILS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 1, 294, 55));

        jLabel2.setText("QUALIFICATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 164, 35));

        jLabel3.setText("DEGREE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 95, 128, 33));

        jLabel4.setText("CLG/SCHOOL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 95, 112, 33));

        jLabel5.setText("BORAD/UNI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 95, 103, 33));

        jLabel6.setText("SUBJECTS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 95, 135, 33));

        jLabel7.setText("PERCENTAGE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 95, 122, 33));

        jLabel8.setText("10TH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 134, -1, 32));

        jLabel9.setText("12TH");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 172, -1, 34));

        jLabel10.setText("GRADUTE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 202, 95, 37));

        jLabel11.setText("P.GRA.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, 95, 37));

        jLabel12.setText("P.H.D");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 288, 95, 37));

        jLabel13.setText("OTHER ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 331, 95, 34));

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.TECH", "B.C.A", "B.Sc", " " }));
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 210, -1, -1));

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M.TECH", "M.C.A", "MSc", " " }));
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 253, -1, -1));

        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES" }));
        getContentPane().add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 288, -1, -1));

        cb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "YES" }));
        getContentPane().add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 331, -1, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 134, 102, 29));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 169, 102, 31));
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 206, 102, 33));
        getContentPane().add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 245, 102, 32));

        t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t17ActionPerformed(evt);
            }
        });
        getContentPane().add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 288, 102, 30));

        t21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t21ActionPerformed(evt);
            }
        });
        getContentPane().add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 324, 102, 27));
        getContentPane().add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 288, 102, 30));
        getContentPane().add(t22, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 324, 102, 27));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 134, 102, 29));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 169, 102, 31));
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 206, 102, 33));
        getContentPane().add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 245, 102, 32));
        getContentPane().add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 288, 102, 30));

        t23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t23ActionPerformed(evt);
            }
        });
        getContentPane().add(t23, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 324, 102, 27));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 134, 102, 29));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 169, 102, 31));
        getContentPane().add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 206, 102, 33));

        t15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t15ActionPerformed(evt);
            }
        });
        getContentPane().add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 245, 102, 32));

        t20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t20ActionPerformed(evt);
            }
        });
        getContentPane().add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 288, 102, 30));

        t24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t24ActionPerformed(evt);
            }
        });
        getContentPane().add(t24, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 324, 102, 27));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 134, 102, 29));
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 169, 102, 31));
        getContentPane().add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 206, 102, 35));

        t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t16ActionPerformed(evt);
            }
        });
        getContentPane().add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 245, 102, 36));

        jLabel14.setText("SELECT YEARS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 373, 143, 35));

        cb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "4", "5+" }));
        getContentPane().add(cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 371, -1, 29));

        jLabel15.setText("ORGANISATION");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 414, 173, 36));

        jLabel16.setText("POST");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 414, 156, 36));

        jLabel17.setText("TO");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 414, 134, 36));

        jLabel18.setText("FROM");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 414, 113, 36));
        getContentPane().add(t25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 456, 173, -1));
        getContentPane().add(t26, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 456, 194, -1));
        getContentPane().add(t27, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 456, 162, -1));
        getContentPane().add(t28, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 456, 151, -1));
        getContentPane().add(t29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 482, 173, -1));
        getContentPane().add(t30, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 482, 194, -1));

        t31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t31ActionPerformed(evt);
            }
        });
        getContentPane().add(t31, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 482, 162, -1));

        t32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t32ActionPerformed(evt);
            }
        });
        getContentPane().add(t32, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 482, 151, -1));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 552, -1, 31));

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 552, -1, 31));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setText("Email ID");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 508, 173, 23));
        getContentPane().add(t33, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 511, 194, -1));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 549, -1, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t20ActionPerformed

    private void t31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t31ActionPerformed

    private void t32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t32ActionPerformed

    private void t15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t15ActionPerformed

    private void t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t16ActionPerformed

    private void t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t17ActionPerformed

    private void t21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t21ActionPerformed

    private void t23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t23ActionPerformed

    private void t24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t24ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tc,tb,ts,tp,tenth,twc,twb,tws,twp,twth,gd,gc,gb,gs,gp,graduate,pgd,pgc,pgb,pgs,pgp,postg,phdd,phdc,phdb,phds,phdp,phd,othd,othc,othb,oths,othp,other,org1,post1,to1,from1,org2,post2,to2,from2,email;
        int yrs;
        tc=t1.getText();
        tb=t2.getText();
        ts=t3.getText();
        tp=t4.getText();
        tenth=tc+" "+tb+" "+ts+" "+tp+" ";
       
        twc=t5.getText();
        twb=t6.getText();
        tws=t7.getText();
        twp=t8.getText();
        twth=twc+" "+twb+" "+tws+" "+twp+" ";
        
        gd=cb1.getSelectedItem().toString();
        gc=t9.getText();
        gb=t10.getText();
        gs=t11.getText();
        gp=t12.getText();
        graduate=gd+" "+gc+" "+gb+" "+gs+" "+gp+" ";
        
        pgd=cb2.getSelectedItem().toString();
        pgc=t14.getText();     
        pgb=t15.getText();
        pgp=t16.getText();
        postg=pgd+" "+" "+pgc+" "+pgb+" "+pgp+" ";
        
        phdd=cb3.getSelectedItem().toString();
        phdc=t18.getText();
        phds=t19.getText();
        phdp=t20.getText();
        
        phd=phdd+" "+phdc+" "+phdp+" "+phds+" ";
        
        othd=cb4.getSelectedItem().toString();
        othc=t21.getText();
        othb=t22.getText();
        oths=t23.getText();
        othp=t24.getText();
        other=othd+" "+othc+" "+othb+" "+oths+" "+othp+" ";
        
        yrs=cb4.getSelectedIndex()+1;
        org1=t25.getText();
        post1=t26.getText();
        to1=t27.getText();
        from1=t28.getText();
        org2=t29.getText();
        post2=t30.getText();
        to2=t31.getText();
        from2=t32.getText();
        email=t33.getText();
        try
        {
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","");
          Statement stmt=(Statement)con.createStatement(); //sends data from form to table
          String query="insert into facultypro values('"+tenth+"','"+twth+"','"+graduate+"','"+postg+"','"+phd+"','"+other+"','"+yrs+"','"+org1+"','"+post1+"','"+to1+"','"+from1+"','"+org2+"','"+post2+"','"+to2+"','"+from2+"','"+email+"');";
          stmt.executeUpdate(query);
        }
           catch(Exception e)
        {
            
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new welcome_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facultypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facultypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facultypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facultypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facultypro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> cb4;
    private javax.swing.JComboBox<String> cb5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t24;
    private javax.swing.JTextField t25;
    private javax.swing.JTextField t26;
    private javax.swing.JTextField t27;
    private javax.swing.JTextField t28;
    private javax.swing.JTextField t29;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t30;
    private javax.swing.JTextField t31;
    private javax.swing.JTextField t32;
    private javax.swing.JTextField t33;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
